"""Shared FastMCP server for the running coach snapshot.

The server is read-only: it exposes the static coach journal generated by
scripts/coach_journal.py and does not touch Neon or Garmin.
"""
from __future__ import annotations

import json
import os
from pathlib import Path
from typing import Any

import httpx
from fastmcp import FastMCP

REPO_ROOT = Path(__file__).resolve().parent
DEFAULT_SNAPSHOT_PATH = REPO_ROOT / ".runtime" / "coach-journal.json"

mcp = FastMCP("Running Coach")


def _snapshot_url() -> str:
    return os.environ.get("COACH_SNAPSHOT_URL", "").strip()


def _snapshot_path() -> Path:
    return Path(os.environ.get("COACH_SNAPSHOT_PATH", str(DEFAULT_SNAPSHOT_PATH)))


def _load_snapshot_url(url: str) -> dict[str, Any]:
    token = os.environ.get("COACH_SNAPSHOT_TOKEN") or os.environ.get("MCP_AUTH_TOKEN", "")
    headers = {"Authorization": f"Bearer {token}"} if token else {}
    response = httpx.get(url, headers=headers, timeout=10)
    response.raise_for_status()
    return response.json()


def load_snapshot() -> dict[str, Any]:
    """Load the latest coach snapshot from an authenticated URL or local file."""
    snapshot_url = _snapshot_url()
    if snapshot_url:
        try:
            return _load_snapshot_url(snapshot_url)
        except Exception as exc:  # noqa: BLE001 - local fallback keeps MCP usable
            print(f"[coach-mcp] snapshot URL failed ({exc}); using local file", flush=True)

    candidate = _snapshot_path().resolve()
    if candidate.exists():
        with candidate.open(encoding="utf-8") as handle:
            return json.load(handle)

    raise FileNotFoundError(f"coach snapshot not found: {candidate}")


def _bounded_count(value: int, default: int = 3, maximum: int = 7) -> int:
    try:
        count = int(value)
    except (TypeError, ValueError):
        count = default
    return max(1, min(maximum, count))


def _recent_runs(snapshot: dict[str, Any], count: int) -> list[dict[str, Any]]:
    runs = snapshot.get("derniers_runs") or []
    return list(runs[:_bounded_count(count)])


def _training_payload(snapshot: dict[str, Any]) -> dict[str, Any]:
    return {
        "genere_le": snapshot.get("genere_le"),
        "objectif": snapshot.get("objectif"),
        "aujourdhui": snapshot.get("seance_du_jour"),
        "projection": snapshot.get("projection", []),
        "zones_allure": snapshot.get("zones_allure"),
        "regle_ajustement": snapshot.get("regle_ajustement"),
    }


def _analysis_payload(snapshot: dict[str, Any], nombre: int = 3) -> dict[str, Any]:
    runs = _recent_runs(snapshot, nombre)
    return {
        "genere_le": snapshot.get("genere_le"),
        "objectif": snapshot.get("objectif"),
        "volume_7j_km": snapshot.get("volume_7j_km"),
        "dernier_run": runs[0] if runs else None,
        "runs": runs,
        "consigne_client": (
            "Analyse la charge recente, la qualite des fractions, l'allure, "
            "la FC moyenne/max et les signaux de fatigue. Termine par un avis "
            "clair sur l'entrainement a faire ensuite."
        ),
    }


@mcp.tool
def journal_du_jour() -> dict[str, Any]:
    """Return the complete coach snapshot: profile, goal, recent runs and plan."""
    return load_snapshot()


@mcp.tool
def entrainement_a_faire() -> dict[str, Any]:
    """Return today's training, next sessions, pace zones and adjustment rule."""
    return _training_payload(load_snapshot())


@mcp.tool
def seance_du_jour() -> dict[str, Any]:
    """Return today's planned session with generation date."""
    snapshot = load_snapshot()
    return {
        "genere_le": snapshot.get("genere_le"),
        **(snapshot.get("seance_du_jour") or {}),
    }


@mcp.tool
def analyse_runs_precedents(nombre: int = 3) -> dict[str, Any]:
    """Return recent runs for coaching analysis, newest first."""
    return _analysis_payload(load_snapshot(), nombre)


@mcp.tool
def sept_derniers_runs() -> dict[str, Any]:
    """Return the 7 latest analyzed runs with splits, pace and heart rate."""
    snapshot = load_snapshot()
    return {
        "genere_le": snapshot.get("genere_le"),
        "volume_7j_km": snapshot.get("volume_7j_km"),
        "runs": snapshot.get("derniers_runs", []),
    }


@mcp.tool
def projection() -> dict[str, Any]:
    """Return the next 3 planned sessions and the coach adjustment rule."""
    snapshot = load_snapshot()
    return {
        "genere_le": snapshot.get("genere_le"),
        "objectif": snapshot.get("objectif"),
        "projection": snapshot.get("projection", []),
        "regle_ajustement": snapshot.get("regle_ajustement"),
    }


@mcp.tool
def zones_allure() -> dict[str, Any]:
    """Return target pace zones for easy, threshold, race pace and VO2max work."""
    snapshot = load_snapshot()
    return {
        "profil": snapshot.get("profil"),
        "zones_allure": snapshot.get("zones_allure"),
    }


@mcp.tool
def poser_question_coach(question: str) -> dict[str, Any]:
    """Return the coach context needed to answer a natural-language question."""
    snapshot = load_snapshot()
    lower_question = (question or "").lower()
    if any(word in lower_question for word in ("aujourd", "seance", "entrainement", "faire")):
        contexte: dict[str, Any] = _training_payload(snapshot)
    elif any(word in lower_question for word in ("run", "course", "preced", "analyse", "dernier")):
        contexte = _analysis_payload(snapshot, 3)
    else:
        contexte = _training_payload(snapshot)
    return {
        "question": question,
        "consigne_client": (
            "Reponds comme un coach running concis, en francais, en utilisant "
            "uniquement ce snapshot. Cite les dates, allures et volumes utiles. "
            "Si la donnee n'est pas dans le snapshot, dis-le clairement."
        ),
        "contexte_selectionne": contexte,
        "snapshot": snapshot,
    }


def create_http_app(path: str = "/"):
    """Create an ASGI app exposing the MCP Streamable HTTP endpoint."""
    return mcp.http_app(path=path)
